apiVersion: v1
kind: ConfigMap
metadata:
  name: bando-fse-privati-be-config-staging
data:
  APP_NAME: "backend-api"
  APP_LOG_LEVEL: "INFO"
  DB_HOST: "rrtgn-sis-pg01-s01.rtpc.sct.toscana.it"
  DB_PORT: "5432"
  DB_NAME: "bando-fse-privati-db"
  DB_USER: "bando-fse-privati-db_rw"
  DB_PASSWORD: "5SQp1k5cX4T2"
  DB_POOL_MIN_SIZE: "1"
  DB_POOL_MAX_SIZE: "10"
  DB_SEARCH_PATH: '"bando-fse-privati-schema",public'
  CORS_ORIGINS: "https://gestionefseprivati-test.sanita.toscana.it,https://gestionefseprivati-test.sanita.toscana.it/bando-fse-privati-fe/,https://gestionefseprivati-test.sanita.toscana.it/bando-fse-privati-fe/callback,https://gestionefseprivati.sanita.toscana.it,https://gestionefseprivati.sanita.toscana.it/bando-fse-privati-fe/,http://localhost:8080,http://127.0.0.1:8080,http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000,http://127.0.0.1:3000,http://localhost:8000,http://127.0.0.1:8000"
