apiVersion: v1
kind: ConfigMap
metadata:
  name: bando-fse-privati-be-config-production
data:
  APP_NAME: "backend-api"
  APP_LOG_LEVEL: "INFO"
  DB_HOST: "rrtgn-sis-pg01-p01.rtpc.sct.toscana.it"
  DB_PORT: "5432"
  DB_NAME: "bando-fse-privati-db"
  DB_USER: "bando-fse-privati-db_rw"
  DB_PASSWORD: "nD4796k93kVD"
  DB_POOL_MIN_SIZE: "1"
  DB_POOL_MAX_SIZE: "10"
  DB_SEARCH_PATH: '"bando-fse-privati-schema",public'
  CORS_ORIGINS: "https://gestionefseprivati.sanita.toscana.it,https://gestionefseprivati.sanita.toscana.it/bando-fse-privati-fe/,https://gestionefseprivati.sanita.toscana.it/bando-fse-privati-fe/callback"
